#!/bin/sh

# https://gist.github.com/lukasnellen/fe9b61cb9add581ef0215bd40c09c7c2

main() {
	QEMU_ARCH=x86_64
	QEMU_DISK=gentoo-amd64.qcow2
	QEMU_PORT=8889
	QEMU_CPUS=1
	QEMU_RAMS=512

	pkgsrc-disk-create-if-needed "${QEMU_DISK}"

	exec qemu-system-${QEMU_ARCH} \
		-machine type=q35,accel=hvf \
		-cpu Nehalem \
		-smp ${QEMU_CPUS} \
		-m ${QEMU_RAMS} \
		-nic user,mac=02:df:5c:b0:20:51,model=e1000,hostfwd=tcp::${QEMU_PORT}-:22,ipv6=off \
		-hda ${QEMU_DISK} \
		-nographic \
		-serial mon:stdio \
		"$@"
}

cd "$(dirname "$0")"
main "$@"
exit $?
