#!/bin/sh

# https://markshroyer.com/2013/01/debugging-openbsd-via-qemu/

main() {
	QEMU_ARCH=x86_64
	QEMU_DISK=openbsd-i386.qcow2
	QEMU_PORT=2231
	QEMU_CPUS=1
	QEMU_RAMS=512

	pkgsrc-disk-create-if-needed "${QEMU_DISK}"

	exec qemu-system-${QEMU_ARCH} \
		-smp ${QEMU_CPUS} \
		-m ${QEMU_RAMS} \
		-nographic \
		-nic user,model=virtio,hostfwd=tcp::${QEMU_PORT}-:22,ipv6=off \
		-drive file=${QEMU_DISK},if=virtio,format=qcow2,index=0 \
		"$@"
}

cd "$(dirname "$0")"
main "$@"
exit $?

#	-serial mon:telnet::2228,server,wait \
#	-cdrom install70.iso -boot d \
