#!/bin/sh

main() {
	QEMU_ARCH=x86_64
	QEMU_DISK=ubuntu-amd64.qcow2
	QEMU_PORT=3436
	QEMU_CPUS=1
	QEMU_RAMS=512

	pkgsrc-disk-create-if-needed "${QEMU_DISK}"

	exec qemu-system-${QEMU_ARCH} \
		-machine type=q35,accel=hvf \
		-cpu Nehalem \
		-smp ${QEMU_CPUS} \
		-m ${QEMU_RAMS} \
		-nic user,mac=02:5f:6e:85:7f:fa,model=virtio,hostfwd=tcp::${QEMU_PORT}-:22,ipv6=off \
		-drive file=${QEMU_DISK},if=virtio,format=qcow2,index=0 \
		-nographic \
		"$@"
}

#		-serial mon:stdio \

cd "$(dirname "$0")"
main "$@"
exit $?
