#!/bin/sh

# https://kimmo.suominen.com/blog/2020/04/serial-console-for-netbsd/

main() {
	QEMU_ARCH=x86_64
	QEMU_DISK=netbsd-amd64.qcow2
	QEMU_PORT=2222
	QEMU_CPUS=1
	QEMU_RAMS=1536

	pkgsrc-disk-create-if-needed "${QEMU_DISK}"

	exec qemu-system-${QEMU_ARCH} \
		-M accel=hvf --cpu host \
		-smp ${QEMU_CPUS} \
		-m ${QEMU_RAMS} \
		-nographic \
		-nic user,mac=02:bd:32:29:98:13,model=virtio,hostfwd=tcp::${QEMU_PORT}-:22,ipv6=off \
		-drive file=${QEMU_DISK},if=virtio,format=qcow2,index=0 \
		"$@"
}

cd "$(dirname "$0")"
main "$@"
exit $?
