#!/bin/sh

main() {
	QEMU_ARCH=sparc
	QEMU_DISK=netbsd-sparc.qcow2
	QEMU_PORT=2225
	QEMU_CPUS=1
	QEMU_RAMS=128

	pkgsrc-disk-create-if-needed "${QEMU_DISK}"

	exec qemu-system-${QEMU_ARCH} \
		-smp ${QEMU_CPUS} \
		-m ${QEMU_RAMS} \
		-nographic \
		-nic user,hostfwd=tcp::${QEMU_PORT}-:22,ipv6=off \
		-drive file=netbsd-sparc.qcow2,if=scsi,bus=0,unit=0,media=disk \
		"$@"
}

#	-net user -net nic

cd "$(dirname "$0")"
main "$@"
exit $?
