#!/bin/sh

main() {
	QEMU_ARCH=x86_64
	QEMU_DISK=netbsd-amd64.qcow2

	QEMU_CPUS=1
	QEMU_RAMS=512

	pkgsrc-disk-create-if-needed "${QEMU_DISK}"

	exec socket_vmnet_client /var/pkg/run/socket_vmnet \
		qemu-system-${QEMU_ARCH} \
		-M accel=hvf --cpu host \
		-smp ${QEMU_CPUS} \
		-m ${QEMU_RAMS} \
		-nographic \
		-drive file=${QEMU_DISK},if=virtio,format=qcow2,index=0 \
		-device virtio-net-pci,netdev=net0,mac=02:04:6a:7f:e3:a4 \
		-netdev socket,id=net0,fd=3 \
		"$@"
}

cd "$(dirname "$0")"
main "$@"
exit $?
