#!/bin/sh

main() {
	QEMU_ARCH=x86_64
	QEMU_DISK=netbsd-amd64.qcow2
	QEMU_PORT=2223
	QEMU_CPUS=1
	QEMU_RAMS=512

	pkgsrc-disk-create-if-needed "${QEMU_DISK}"

	exec qemu-system-${QEMU_ARCH} \
		-M accel=hvf --cpu host \
		-smp ${QEMU_CPUS} \
		-m ${QEMU_RAMS} \
		-nographic \
		-nic user,model=virtio,hostfwd=tcp::${QEMU_PORT}-:22,ipv6=off \
		-drive file=${QEMU_DISK},if=virtio,format=qcow2,index=0 \
		"$@"
}

cd "$(dirname "$0")"
main "$@"
exit $?
